### ISSUE TITLE
Is reverse proxy required/recommended? 

### ISSUE THREAD

**Issue by krikkert** [Kailona/ehr#101]
I run Traefik instead of nginx (would be happy to help provide docs on setting up with traefik, by the way), but as I prefer not opening services up on the internet unless I must, I've attempted setting up FHIR without any reverse proxy (it's enabled in traefik, but without any entry points). 

In the docker-compose file, I add FHIR to a Docker network wherein Nextcloud already is situated. In Nextcloud's EHR settings, I simply enter "http://fhir:9080/fhir-server/api/v4/" (thus pointing it to the FHIR server on its own internal Docker network). As the network traffic is entirely between two Docker containers, HTTPS is not necessary. 

I think such a setup would be a lot simpler (could possibly even make automated setting up in Nextcloud-EHR possible).

**Comment by ayselafsar** [comment]
I think that is a secure setup. We recommend that FHIR server is not open to public internet. However, if it is open for other purposes, then FHIR server and Nextcloud must use HTTPS.

We would appreciate the pull requests with scripts or docs to simplify environment setup. Thanks!
