### ISSUE TITLE
Crucial Documentation Improvement

### ISSUE THREAD

**Issue by ttbek** [Kailona/ehr#55]
The documentation available here: https://docs.kailona.org/docs/  (including the link to the info here: https://docs.kailona.org/docs/guides/setup-fhir-server/) NEEDS to be in the description in the NextCloud Store here: https://apps.nextcloud.com/apps/ehr 

Otherwise new users will install the NextCloud app without having an FHIR server and it doesn't look merely alpha, it makes it look like an epic fail loading absolutely nothing, not even an error message.

**Comment by ayselafsar** [comment]
Hi @ttbek,
Thanks for the report. We'll have it in the next release.
