### ISSUE TITLE
Transifex translations

### ISSUE THREAD

**Issue by Valdnet** [Kailona/ehr#67]
Transifex translations have not been downloaded for a long time. Is our work wasted  :grimacing:?

**Comment by ayselafsar** [comment]
Sorry for the delay, we had a problem with nextcloud-bot access. Hope they will be downloaded soon. Your valuable work should never be wasted. Thanks!

**Comment by ayselafsar** [comment]
We have some missing strings to flag for translation in the code base. I will use this ticket for them.
