### ISSUE TITLE
Be able to share medical data / patient profiles and create more than only the personal one

### ISSUE THREAD

**Issue by MaxGitHubAccount** [Kailona/ehr#83]
Since https://github.com/Kailona/ehr/issues/15 which is a very important feature (as I don't want to share my medical data with everyone on my nextcloud instance) I can only see my own medical data.
There are two problems with the current solution:
1. It seems that the selection if to show or not to show can be tricked. I created a second nextcloud instance with the same user name and shared the FHIR system - I could see the same medical data again.
2. I tried to create a patient profile for my son and want to be able to share the patient information with my wife. When creating new patient profiles I cannot see them in my nextcloud instance.

**Comment by ayselafsar** [comment]
Thanks for the report.

1. Great catch! We were looking for such a testing and will fix it soon. Let us know if you see any other issues on this area.

2. We are working on a new feature to share patient information among Nextcloud users, using the same FHIR server.

**Comment by onur-dogan** [comment]
1. Unable to reproduce: This was already fixed.
2. This will be done by #61
